# Generated by Django 3.2 on 2021-05-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patient_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=122)),
                ('gender', models.CharField(max_length=122)),
                ('age', models.CharField(max_length=122)),
                ('date_adm', models.CharField(max_length=122)),
                ('diagnosis', models.CharField(max_length=122)),
                ('prescription', models.CharField(max_length=122)),
                ('nok_add', models.CharField(max_length=122)),
                ('hosp_name', models.CharField(max_length=122)),
                ('ward', models.CharField(max_length=122)),
            ],
        ),
    ]
