# Generated by Django 3.2 on 2021-05-11 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_patient_data_hosp_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_data',
            name='hosp_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.hospitals'),
        ),
    ]
